### ISSUE TITLE
Import-AzSentinelAlertRule: Issue

### ISSUE THREAD

**Issue by KrishhnaM** [OfficeDev/O365-ActivityFeed-AzureFunction#3]
Hi,
I am trying to create the Office 365 DLP rules in sentinel, stuck with below error
//Error//
**Import-AzSentinelAlertRule:
Line |
  18 |  … tem $file | Import-AzSentinelAlertRule -WorkspaceName $workspacename  …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Unable to invoke webrequest with error message: Response status code does not indicate success: 400 (Bad Request).**
//Error//

**Below details verbrose for reference**
//Verbrose//
VERBOSE: Rule Identified_PII_Data_in_Cloud_Low doesn't exist in Azure Sentinel
VERBOSE: Creating new rule: Identified_PII_Data_in_Cloud_Low
VERBOSE: PUT https://management.azure.com/subscriptions/ca6d3f14-Removed-47d2-bd39-57313ef18abc/resourcegroups/sentinel-lab-rg/providers/microsoft.operationalinsights/workspaces/sentinellabws/providers/Microsoft.SecurityInsights/alertRules/db1c463c-17ea-44fa-9dfe-removeda66a758?api-version=2019-01-01-preview with 1624-byte payload
VERBOSE: received 401-byte response of content type application/json
VERBOSE: {"error":{"code":"BadRequest","message":"FailedToResolveScalarExpression; Message: {\"error\":{\"message\":\"The request had some invalid properties\",\"code\":\"BadArgumentError\",\"innererror\":{\"code\":\"SemanticError\",\"message\":\"A semantic error occurred.\",\"innererror\":{\"code\":\"SEM0100\",\"message\":\"'extend' operator: Failed to resolve scalar expression named 'ObjectId_s'\"}}}};"}}
Import-AzSentinelAlertRule:

**Comment by jonnords** [comment]
Usually this is because you don't have events from both SharePoint and Exchange. From the verbose output you can see that it is successfully connected to your Sentinel instance. But fails upon rule creation.

**Comment by jonnords** [comment]
Closing this for now please ask again if you don't get it to work.
