### ISSUE TITLE
Event Data might be truncated when DLP.ALL (Exchange) log is over 32k

### ISSUE THREAD

**Issue by desmphil** [OfficeDev/O365-ActivityFeed-AzureFunction#4]
When sending over 200 sensitive info type in an email, event Data might be truncated in the O365DLP_CL Sentinel log.

This is due to a limit over the Log Analytics Data.

The solution is to reduce the Depth over the JSON conversion until we truncate the data correctly.

$jsonus = $usWorkspace | convertTo-Json -depth 8 or 9 max

**Comment by jonnords** [comment]
I will change the depth in the code thank you for a good find.

**Comment by desmphil** [comment]
I also had other location with 40905 characters, I used this to truncate data in the meantime's

    if ($user.policydetails.rules.ConditionsMatched.SensitiveInformation.location.length -gt 200){
    $user.policydetails.rules.ConditionsMatched.SensitiveInformation = "DATA TRUNCATED TOO LONG"}

**Comment by desmphil** [comment]
To find out if you are maxing out the Long Analytics Size

O365DLP_CL 
| where Operation_s == "DlpRuleMatch"
| extend len = strlen(PolicyDetails_s)

**Comment by jonnords** [comment]
This code seems to do the trick. I've been testing it for a while. I will update in the next week.

if ($user.PolicyDetails.rules.ConditionsMatched.SensitiveInformation.SensitiveInformationDetections.ResultsTruncated -eq "true") {
$detectedrows = $user.PolicyDetails.rules.ConditionsMatched.SensitiveInformation.SensitiveInformationDetections.DetectedValues.count
do      {
    $increment = [math]::truncate($detectedrows/2 )
    $detected = $user.PolicyDetails.rules.ConditionsMatched.SensitiveInformation.SensitiveInformationDetections.DetectedValues[0..$increment]
    $detectedcount = $detected.value | Measure-object -Character
    $detectedrows = [math]::truncate($increment*1.5)
        } until ($detectedcount.Characters -le "10240" )
            $user.PolicyDetails.rules.ConditionsMatched.SensitiveInformation.SensitiveInformationDetections.DetectedValues = $detected

**Comment by jonnords** [comment]
The code has been updated and committed to the function.
