### ISSUE TITLE
Time tracker may get reset or empty

### ISSUE THREAD

**Issue by desmphil** [OfficeDev/O365-ActivityFeed-AzureFunction#5]
You may get issue where the TimeTracker gets deleted or Empty.
You may then validate with the Azure Function App console that the two audit.dlp.log and audit.general.log are empty

_`2020-10-27T14:20:31.932 [Error] ERROR: Cannot bind parameter 'Start' to the target. Exception setting "Start": "Cannot convert null to type "System.DateTime"."Exception             :Type              : System.Management.Automation.ParameterBindingExceptionMessage           : Cannot bind parameter 'Start' to the target. Exception setting "Start": "Cannot convert null to type "System.DateTime"."ParameterName     : StartParameterType     : datetimeErrorId           : ParameterBindingFailedLine              : 37Offset            : 35CommandInvocation :MyCommand        : New-TimeSpanScriptLineNumber : 37OffsetInLine     : 15HistoryId        : 1ScriptName       : D:\home\site\wwwroot\QueueDLPEvents\run.ps1Line             : $adjustTime = New-TimeSpan -start $storedTime -End $endTimePositionMessage  : At D:\home\site\wwwroot\QueueDLPEvents\run.ps1:37 char:15+ $adjustTime = New-TimeSpan -start $storedTime -End $endTime+               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~PSScriptRoot     : D:\home\site\wwwroot\QueueDLPEventsPSCommandPath    : D:\home\site\wwwroot\QueueDLPEvents\run.ps1InvocationName   : New-TimeSpanPipelineLength   : 1PipelinePosition : 1CommandOrigin    : InternalErrorRecord       :Exception             :Type    : System.Management.Automation.ParentContainsErrorRecordExceptionMessage : Cannot bind parameter 'Start' to the target. Exception setting "Start": "Cannot convert null to type "System.DateTime"."HResult : -2146233087CategoryInfo          : WriteError: (:) [New-TimeSpan], ParentContainsErrorRecordExceptionFullyQualifiedErrorId : ParameterBindingFailed,Microsoft.PowerShell.Commands.NewTimeSpanCommandInvocationInfo        :MyCommand        : New-TimeSpanScriptLineNumber : 37OffsetInLine     : 35HistoryId        : 1ScriptName       : D:\home\site\wwwroot\QueueDLPEvents\run.ps1Line             : $adjustTime = New-TimeSpan -start $storedTime -End $endTimePositionMessage  : At D:\home\site\wwwroot\QueueDLPEvents\run.ps1:37 char:35+ $adjustTime = New-TimeSpan -start $storedTime -End $endTime+                                   ~~~~~~~~~~~PSScriptRoot     :`_

**Solution RE-RUN Enablements**

**Comment by jonnords** [comment]
The Timespan function is in there for cases where a function may not trigger for several days. The case of a missing tracking log files would be more serious since it is set when you run the enablement script and is not expected to live. For now the best alternative is as you suggest re-run the enablement script it will also reset the timing for synchronizing Policy rules.

Thank you for a  good solution that can be used by others.
