### ISSUE TITLE
No parameter defined in the script or function for the input binding 'req'

### ISSUE THREAD

**Issue by marikb** [OfficeDev/O365-ActivityFeed-AzureFunction#8]
Hello,
I followed this tutorial for Using the Office 365 Management Activity API and Power BI for security analysis (Part 1)[https://techcommunity.microsoft.com/t5/microsoft-security-and/using-the-office-365-management-activity-api-and-power-bi-for/ba-p/189086](url) which led me here to **enablebysubsciption.ps1** on Enable Subscription stage.

When I run the script in cloud shell, I'm getting a "No parameter defined in the script or function for the input binding 'req'" error.
Could you explain what is gone wrong? I made the proper changes in Function(code), Integration(HTTP), and Outputs (Cosmos DB) as told.

**Comment by jonnords** [comment]
Please try to use the /V2Function_Investigate/EnableSubscription.ps1. The req parameter shouldn't be in this script.

**Comment by marikb** [comment]
Running _/V2Function_Investigate/EnableSubscription.ps1_ worked for me. Thank you for that.
Now I'm getting this error when I'm trying to run **ActivityFunctionApp.ps1**

Any help with that?

**Comment by jonnords** [comment]
That code cannot run in Cloud Shell it has to be executed from an Azure Function. If you want to run it through cloudshell you would have to customize the code.

**Comment by marikb** [comment]
Obviously, I'm running it as an HTTP trigger function:

![image](https://user-images.githubusercontent.com/32127651/107861622-c2868680-6e4f-11eb-8db4-4df675cc45aa.png)

**Comment by marikb** [comment]
Any updates on that?

**Comment by jonnords** [comment]
I think that it may be that the HTTP trigger function works a bit different in the Azure function v3. So you will likely have to change it a bit. A word of warning is that it is not recommended to connect to the O365 Activity API with Webhooks any more. That is why more recent code is using a Timer function to pull.

**Comment by marikb** [comment]
Figured it out in code based on suggestions given. Thank you @jonnords (Closing issue)
